### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by nmeisels** [ronreiter/learntotype#3]
Hi!

My son(4.5y) absolutely loves this game!
He asked if I can add negative numbers and more features (english language etc..) :) 
Can you enlighten me a bit.
1. How do you generate the sounds?
2. How do you create the svg images?

Thanks!

**Comment by ronreiter** [comment]
1. I use the Mac command line "say" command for that
2. Well, you download them from somewhere or make them using Illustrator. There are many free ones online.
